- hosts: localhost
  connection: local
  
  tasks:
  - name: Create & Start Container
    docker_container:
      name: hello-world
      image: "swgu931/hello-world:{{ lookup('env','BUILD_NUMBER') }}"
      state: started
      ports:
      - "80:8080"
